version: 0.0
os: linux
files:
   - source: /home/ec2-user/deploy/sample.war
     destination: /usr/share/tomcat6/webapps/
permissions:
   - object: /usr/share/tomcat6/webapps/sample.war
     pattern: "**"
     owner: ec2-user
     group: ec2-user
     mode: 755
     type:
       - file
hooks:
   BeforeInstall:
    - location: scripts/downloadapp.sh
      runas: ec2-user
    - location: scripts/stoptomcat6.sh
      runas: ec2-user
   AfterInstall:
    - location: scripts/starttomcat6
      runas: ec2-user
